yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug>', views.group_posts, name='group_list'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )

    class Meta:
        ordering = ['-pub_date']

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Group, Post
POSTS_ON_PAGE = 10


def index(request):
    template = 'posts/index.html'
    posts = Post.objects.select_related()[:POSTS_ON_PAGE]
    context = {
        'posts': posts,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()[:POSTS_ON_PAGE]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, template, context)

yatube/templates/base.html
<!-- templates/base.html -->
{% load static %}
<!DOCTYPE html> 
<html lang="ru">
  <head>
    {% include 'includes/head.html' %}
  </head>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      <div class="container py-5">
        <article>
          {% block content %}
          {% endblock %}
        </article>
      </div>  
    </main>
    <footer>
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html> 

yatube/templates/includes/card_post.html
<h1>{{ slug }}</h1>
<ul>
  <li>
    Автор: {{ post.author.get_full_name }}
  </li>
  <li>
    Группа: {{ post.group }}
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
</ul>
<p>{{ post.text }}</p>    
{% if  link_index %}
  <a href="{% url 'posts:group_list' link_index %}">Посмотреть записи группы</a>
{% else %}
  <a href="{% url 'posts:index' %}">На главную</a>
{% endif %}
  <br>
{% if not forloop.last %}<hr>{% endif %}

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/head.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">     
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" href="img/fav/fav.ico" type="image">
<link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
<meta name="msapplication-TileColor" content="#000">
<meta name="theme-color" content="#ffffff">
<title>Yatube для авторов</title>

yatube/templates/includes/header.html
<header>
    {% load static %}
<!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="{% url 'posts:index' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube
          </a>
        </div>
      </nav> 
</header>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
  {% block content %}
    <h1>Записи сообщества {{ group }}</h1>
    {% for post in posts %}
      {% include 'includes/card_post.html'%}
    {% endfor %} 
  {% endblock content %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
  {% block content %}
    <h1>Yatube для авторов</h1>
    {% for post in posts %}
      {% include 'includes/card_post.html' with link_index=post.group.slug %}
    {% endfor %} 
  {% endblock content %}